#!/usr/bin/perl -w
use strict;

use DBI;

my $data_source = q/dbi:ODBC:DESKTOP-6KS0MN2\SQLEXPRESS/;
my $user = q/shrihari_h/;
my $password = q/shri@123/;

# Connect to the data source and get a handle for that connection.
my $dbh = DBI->connect($data_source, $user, $password)
    or die "Can't connect to $data_source: $DBI::errstr";